import { type NextPage } from "next";
import Head from "next/head";
import { api } from "utils/api";
import { useState } from "react";
import { Movie } from "server/api/routers/tmdb";
import ErrorHandler from "error-handler";
import { MoviesBoxArts } from "components/movieBoxArts.component";
import Loading from "components/loading.component";
import SearchBar from "components/search.component";

const Home: NextPage = () => {
  const playingNow = api.tmdb.now_playing.useQuery();
  const [text, setText] = useState("pokemon");
  return (
    <>
      <div className="m-8">
        <Head>
          <title>Creathus</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="items-center justify-center">
          <h1 className="my-4 text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Creathus <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>{" "}
          <SearchBar />
          <h2
            // make a bigger text with orange color
            className="text-3xl font-extrabold tracking-tight text-orange-500  sm:text-[2rem]"
          >
            Ultimos lancamentos no cinema
          </h2>
          <div className="mt-4 grid grid-cols-7 gap-4">
            {playingNow.data ? (
              <>{playingNow.data.map((todo: Movie) => MoviesBoxArts(todo))}</>
            ) : playingNow?.error?.message == null ? (
              <Loading />
            ) : (
              <ErrorHandler error={playingNow.error?.message} />
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
