import { Stars } from "components/stars.component";
import ErrorHandler from "error-handler";
import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "utils/api";
import { SnackbarProvider, enqueueSnackbar } from "notistack";

// const { data: sessionData } = useSession();
export default function MoviePage(user) {
  const router = useRouter();
  const { id } = router.query;
  const { mutate } = api.tmdb.saveLike.useMutation();

  const movieData =
    typeof id === "string" ? api.tmdb.findMovie.useQuery({ id }) : null;

  if (movieData?.data != null) {
    const saveMovie = async () => {
      try {
        mutate({
          movieId: movieData.data.id,
          userId: user.user,
        });
        enqueueSnackbar("Filme Curtido com sucesso!", { variant: "success" });
      } catch (error) {}
    };
    const imageUrl =
      "https://image.tmdb.org/t/p/original/" + movieData.data.backdrop_path;

    return (
      <div
        className="relative flex h-screen  items-center gap-2"
        style={{ backgroundImage: `url(${imageUrl})`, backgroundSize: "cover" }}
      >
        <Head>
          <title>{movieData.data.title ?? movieData.data.original_title}</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className=" inset-0 bg-black bg-opacity-0 transition-opacity duration-300 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white opacity-0 transition-opacity duration-300 hover:opacity-100"></h1>
          <div className="my-40 flex flex-col items-center gap-2">
            <>
              <h1 className=" text p-16 text-7xl font-extrabold tracking-tight text-orange-500 opacity-100 transition-opacity duration-300 hover:opacity-90">
                {movieData.data.title}
              </h1>
              <h1 className="px-2">
                {movieData.data.genres?.map((genre) => (
                  <div
                    key={genre.id}
                    className="center relative m-1 inline-block select-none whitespace-nowrap rounded-lg bg-pink-500 px-3.5 py-2 align-baseline font-sans text-xs font-bold uppercase leading-none text-white"
                  >
                    {genre.name}
                  </div>
                ))}
              </h1>
              <Stars rating={movieData.data.vote_average} />
              <div className="card-body w-1/3 rounded-xl bg-black bg-opacity-90 shadow-xl shadow-orange-500">
                <p className="flex-wrap text-justify text-base text-white opacity-100 transition-opacity duration-300 hover:opacity-90 ">
                  {movieData.data.overview || "Este filme não possui sinopse"}
                </p>
              </div>
            </>
          </div>

          <button
            onClick={saveMovie}
            className="absolute bottom-0 right-0 m-2 rounded-xl bg-orange-500 p-2 text-white"
          >
            convertMovieApiToEntity
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="grid min-h-screen place-content-center">
      <div className="flex items-center gap-2 text-gray-500">
        <span className="block h-16 w-16 animate-spin rounded-full border-4 border-t-blue-300"></span>
        Carregando...
        <ErrorHandler error={movieData?.error?.data} />
      </div>
    </div>
  );
}

// getServerSideProps
export async function getServerSideProps<getServerSideProps>(context) {
  // get user session
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: {
      user: session.user.id,
    },
  };
}
